export type Field={name:string;label:string;type?:"text"|"email"|"number"|"date"|"textarea"|"select"|"relation";required?:boolean;options?:{value:string;label:string}[];relation?:string};
export type ResourceConfig={slug:string;table:string;singular:string;plural:string;description:string;columns:string[];fields:Field[];numberType?:string;adminOnly?:boolean};
const status=[{value:"active",label:"Ativo"},{value:"inactive",label:"Inativo"}];
const person=[{value:"pf",label:"Pessoa física"},{value:"pj",label:"Pessoa jurídica"}];
const payment=[{value:"cash",label:"Dinheiro"},{value:"credit_card",label:"Cartão de crédito"},{value:"debit_card",label:"Cartão de débito"},{value:"pix",label:"PIX"},{value:"boleto",label:"Boleto"},{value:"other",label:"Outro"}];
const address:Field[]=[{name:"postal_code",label:"CEP"},{name:"street",label:"Endereço"},{name:"number",label:"Número"},{name:"complement",label:"Complemento"},{name:"neighborhood",label:"Bairro"},{name:"city",label:"Cidade"},{name:"state",label:"UF"}];
export const resources:Record<string,ResourceConfig>={
 clientes:{slug:"clientes",table:"customers",singular:"Cliente",plural:"Clientes",description:"Cadastro e histórico de clientes",columns:["name","document","phone","email","status"],fields:[{name:"type",label:"Tipo",type:"select",options:person},{name:"name",label:"Nome / Razão social",required:true},{name:"trade_name",label:"Nome fantasia"},{name:"document",label:"CPF / CNPJ"},{name:"state_registration",label:"Inscrição estadual"},{name:"phone",label:"Telefone"},{name:"whatsapp",label:"WhatsApp"},{name:"email",label:"E-mail",type:"email"},...address,{name:"notes",label:"Observações",type:"textarea"},{name:"status",label:"Status",type:"select",options:status}]},
 veiculos:{slug:"veiculos",table:"vehicles",singular:"Veículo",plural:"Veículos",description:"Veículos vinculados aos clientes",columns:["plate","customer_id","year_model","color","status"],fields:[{name:"customer_id",label:"Cliente",type:"relation",relation:"customers",required:true},{name:"vehicle_brand_id",label:"Marca",type:"relation",relation:"vehicle_brands"},{name:"vehicle_model_id",label:"Modelo",type:"relation",relation:"vehicle_models"},{name:"plate",label:"Placa",required:true},{name:"version",label:"Versão"},{name:"year_manufacture",label:"Ano fabricação"},{name:"year_model",label:"Ano modelo"},{name:"color",label:"Cor"},{name:"chassis",label:"Chassi"},{name:"odometer",label:"Quilometragem",type:"number"},{name:"notes",label:"Observações",type:"textarea"},{name:"status",label:"Status",type:"select",options:status}]},
 produtos:{slug:"produtos",table:"products",singular:"Produto ou serviço",plural:"Produtos e serviços",description:"Catálogo, preços e saldo de estoque",columns:["name","sku","type","sale_price","stock_quantity","status"],fields:[{name:"type",label:"Tipo",type:"select",required:true,options:[{value:"product",label:"Produto"},{value:"service",label:"Serviço"}]},{name:"name",label:"Nome",required:true},{name:"sku",label:"SKU"},{name:"barcode",label:"Código de barras"},{name:"description",label:"Descrição",type:"textarea"},{name:"unit",label:"Unidade"},{name:"cost_price",label:"Preço de custo",type:"number"},{name:"sale_price",label:"Preço de venda",type:"number"},{name:"stock_minimum",label:"Estoque mínimo",type:"number"},{name:"category",label:"Categoria"},{name:"brand",label:"Marca"},{name:"ncm",label:"NCM"},{name:"status",label:"Status",type:"select",options:status}]},
 fornecedores:{slug:"fornecedores",table:"suppliers",singular:"Fornecedor",plural:"Fornecedores",description:"Cadastro de fornecedores",columns:["name","document","contact_name","phone","status"],fields:[{name:"type",label:"Tipo",type:"select",options:person},{name:"name",label:"Nome / Razão social",required:true},{name:"trade_name",label:"Nome fantasia"},{name:"document",label:"CPF / CNPJ"},{name:"state_registration",label:"Inscrição estadual"},{name:"contact_name",label:"Contato"},{name:"phone",label:"Telefone"},{name:"whatsapp",label:"WhatsApp"},{name:"email",label:"E-mail",type:"email"},...address,{name:"notes",label:"Observações",type:"textarea"},{name:"status",label:"Status",type:"select",options:status}]},
 "ordens-servico":{slug:"ordens-servico",table:"service_orders",singular:"Ordem de serviço",plural:"Ordens de serviço",description:"Execução e acompanhamento dos serviços",columns:["number","customer_id","vehicle_id","status","total","opened_at"],numberType:"service_order",fields:[{name:"customer_id",label:"Cliente",type:"relation",relation:"customers",required:true},{name:"vehicle_id",label:"Veículo",type:"relation",relation:"vehicles"},{name:"status",label:"Status",type:"select",options:[{value:"draft",label:"Rascunho"},{value:"open",label:"Aberta"},{value:"in_progress",label:"Em andamento"},{value:"completed",label:"Concluída"},{value:"cancelled",label:"Cancelada"}]},{name:"complaint",label:"Reclamação",type:"textarea"},{name:"diagnosis",label:"Diagnóstico",type:"textarea"},{name:"discount",label:"Desconto",type:"number"},{name:"total",label:"Total",type:"number"},{name:"opened_at",label:"Abertura",type:"date"},{name:"internal_notes",label:"Observações internas",type:"textarea"}]},
 estoque:{slug:"estoque",table:"stock_movements",singular:"Movimentação",plural:"Estoque",description:"Saldos e movimentações de produtos",columns:["product_id","type","quantity","reason","created_at"],fields:[{name:"product_id",label:"Produto",type:"relation",relation:"products",required:true},{name:"type",label:"Tipo",type:"select",required:true,options:[{value:"entry",label:"Entrada"},{value:"exit",label:"Saída"},{value:"adjustment",label:"Ajuste"}]},{name:"quantity",label:"Quantidade",type:"number",required:true},{name:"unit_cost",label:"Custo unitário",type:"number"},{name:"reason",label:"Motivo",type:"textarea"}]},
 vendas:{slug:"vendas",table:"sales",singular:"Venda",plural:"Vendas",description:"Vendas e recebimentos",columns:["number","customer_id","status","payment_method","total","created_at"],numberType:"sale",fields:[{name:"customer_id",label:"Cliente",type:"relation",relation:"customers"},{name:"status",label:"Status",type:"select",options:[{value:"open",label:"Aberta"},{value:"completed",label:"Concluída"},{value:"cancelled",label:"Cancelada"}]},{name:"payment_method",label:"Pagamento",type:"select",options:payment},{name:"subtotal",label:"Subtotal",type:"number"},{name:"discount",label:"Desconto",type:"number"},{name:"total",label:"Total",type:"number"},{name:"notes",label:"Observações",type:"textarea"}]},
 orcamentos:{slug:"orcamentos",table:"quotes",singular:"Orçamento",plural:"Orçamentos",description:"Propostas comerciais",columns:["number","customer_id","status","valid_until","total"],numberType:"quote",fields:[{name:"customer_id",label:"Cliente",type:"relation",relation:"customers"},{name:"vehicle_id",label:"Veículo",type:"relation",relation:"vehicles"},{name:"status",label:"Status",type:"select",options:[{value:"draft",label:"Rascunho"},{value:"sent",label:"Enviado"},{value:"approved",label:"Aprovado"},{value:"rejected",label:"Rejeitado"},{value:"expired",label:"Expirado"}]},{name:"valid_until",label:"Validade",type:"date"},{name:"subtotal",label:"Subtotal",type:"number"},{name:"discount",label:"Desconto",type:"number"},{name:"total",label:"Total",type:"number"},{name:"notes",label:"Observações",type:"textarea"}]},
 garantias:{slug:"garantias",table:"warranties",singular:"Garantia",plural:"Garantias",description:"Controle de garantias",columns:["number","customer_id","status","start_date","end_date"],numberType:"warranty",fields:[{name:"customer_id",label:"Cliente",type:"relation",relation:"customers",required:true},{name:"vehicle_id",label:"Veículo",type:"relation",relation:"vehicles"},{name:"service_order_id",label:"Ordem de serviço",type:"relation",relation:"service_orders"},{name:"description",label:"Descrição",type:"textarea"},{name:"status",label:"Status",type:"select",options:[{value:"active",label:"Ativa"},{value:"claimed",label:"Acionada"},{value:"expired",label:"Expirada"},{value:"voided",label:"Anulada"}]},{name:"start_date",label:"Início",type:"date"},{name:"end_date",label:"Fim",type:"date"},{name:"terms",label:"Termos",type:"textarea"},{name:"claim_notes",label:"Notas de acionamento",type:"textarea"}]},
 compras:{slug:"compras",table:"purchases",singular:"Compra",plural:"Compras",description:"Pedidos e entradas de fornecedores",columns:["number","supplier_id","invoice_number","status","total"],numberType:"purchase",fields:[{name:"supplier_id",label:"Fornecedor",type:"relation",relation:"suppliers"},{name:"invoice_number",label:"Nota fiscal"},{name:"status",label:"Status",type:"select",options:[{value:"draft",label:"Rascunho"},{value:"ordered",label:"Pedida"},{value:"received",label:"Recebida"},{value:"cancelled",label:"Cancelada"}]},{name:"subtotal",label:"Subtotal",type:"number"},{name:"discount",label:"Desconto",type:"number"},{name:"shipping",label:"Frete",type:"number"},{name:"total",label:"Total",type:"number"},{name:"expected_date",label:"Previsão",type:"date"},{name:"received_date",label:"Recebimento",type:"date"},{name:"notes",label:"Observações",type:"textarea"}]},
 financeiro:{slug:"financeiro",table:"financial_entries",singular:"Lançamento",plural:"Financeiro",description:"Contas a pagar e receber",columns:["description","type","status","amount","due_date","paid_date"],fields:[{name:"type",label:"Tipo",type:"select",required:true,options:[{value:"receivable",label:"A receber"},{value:"payable",label:"A pagar"}]},{name:"description",label:"Descrição",required:true},{name:"category",label:"Categoria"},{name:"amount",label:"Valor",type:"number",required:true},{name:"status",label:"Status",type:"select",options:[{value:"pending",label:"Pendente"},{value:"paid",label:"Pago"},{value:"overdue",label:"Vencido"},{value:"cancelled",label:"Cancelado"}]},{name:"due_date",label:"Vencimento",type:"date"},{name:"paid_date",label:"Pagamento",type:"date"},{name:"paid_amount",label:"Valor pago",type:"number"},{name:"payment_method",label:"Forma de pagamento",type:"select",options:payment},{name:"customer_id",label:"Cliente",type:"relation",relation:"customers"},{name:"supplier_id",label:"Fornecedor",type:"relation",relation:"suppliers"},{name:"notes",label:"Observações",type:"textarea"}]},
 caixa:{slug:"caixa",table:"cash_registers",singular:"Caixa",plural:"Caixas",description:"Abertura, lançamentos e fechamento",columns:["status","opening_balance","closing_balance","opened_at","closed_at"],fields:[{name:"opening_balance",label:"Saldo inicial",type:"number",required:true},{name:"closing_balance",label:"Saldo final",type:"number"},{name:"status",label:"Status",type:"select",options:[{value:"open",label:"Aberto"},{value:"closed",label:"Fechado"}]},{name:"notes",label:"Observações",type:"textarea"}]},
 filiais:{slug:"filiais",table:"branches",singular:"Filial",plural:"Filiais",description:"Unidades da empresa",columns:["name","code","document","city","status"],fields:[{name:"name",label:"Nome",required:true},{name:"code",label:"Código"},{name:"document",label:"CNPJ"},{name:"email",label:"E-mail",type:"email"},{name:"phone",label:"Telefone"},...address,{name:"status",label:"Status",type:"select",options:status}]},
 usuarios:{slug:"usuarios",table:"company_users",singular:"Usuário",plural:"Usuários",description:"Acessos e permissões da empresa",columns:["user_id","role","is_active","created_at"],adminOnly:true,fields:[{name:"user_id",label:"ID do usuário no Supabase",required:true},{name:"role",label:"Perfil",type:"select",options:[{value:"owner",label:"Proprietário"},{value:"admin",label:"Administrador"},{value:"manager",label:"Gerente"},{value:"user",label:"Usuário"}]},{name:"is_active",label:"Ativo",type:"select",options:[{value:"true",label:"Sim"},{value:"false",label:"Não"}]}]}
};
export function getResource(slug:string){return resources[slug]}
